version: "3.9"   

services:
  db:
    image: postgres:16
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy
      POSTGRES_DB: devise_omniauth1
  web:
    tty: true        
    stdin_open: true 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails_devise_oauth
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
    driver: local
    
